name: gail_chat_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^2.14.0 #for integrating firebase

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  #google_fonts: ^5.1.0
  date_time_picker: ^2.1.0
  phone_number: ^2.0.1

  #for handling google sign in  
  google_sign_in: ^6.1.4
  
  cloud_firestore: ^4.8.2    # For accessing cloud firestore database
  
  #for shwoing network image profile picture
  cached_network_image: ^3.2.3
  
  #for picking images
  image_network: ^2.5.4+1
  
  provider: ^6.0.5
  
  #for picking images
  image_picker: ^1.0.1

  shared_preferences: ^2.2.0
  
  #For accessing Firebase storage (for uploading files)
  firebase_storage: ^11.2.5

  #for showing emojis
  emoji_picker_flutter: ^1.6.1

  plugin_platform_interface: ^2.1.5

  #For accessing firebase messaging (push Notification)
  firebase_messaging: ^14.6.5

  #for calling RestAPIs 
  http: ^0.13.1

  #for creating notification channel
  flutter_notification_channel: ^2.0.0
  firebase_auth: ^4.7.2
  google_fonts: ^4.0.4
  gallery_saver: ^2.3.2
    
  #for handling firebase authencation
firebase_auth: ^4.7.2
 
  #For storing images into gallery
gallery_saver: ^2.3.2

#for google fonts
google_fonts: ^5.1.0

cloud_firestore: ^2.5.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/cloud-messaging.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  
flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  
    - "assets/images/"
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
